include: package:flutter_lints/flutter.yaml



analyzer:
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    # Reglas de estilo extendidas
    always_declare_return_types: true
    always_specify_types: true
    prefer_double_quotes: true  # Si prefieres comillas simples, esta debe ser false
    use_key_in_widget_constructors: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_final_fields: true
    prefer_const_literals_to_create_immutables: true
    prefer_relative_imports: true
    sort_child_properties_last: true
    annotate_overrides: true

    # Reglas de rendimiento extendidas
    avoid_print: true
    avoid_web_libraries_in_flutter: true
    avoid_unnecessary_containers: true
    avoid_slow_async_io: true
    avoid_empty_else: true
    avoid_dynamic_calls: true
    avoid_as: true
    prefer_typing_uninitialized_variables: true
    avoid_js_rounded_ints: true

    # Reglas de mantenibilidad extendidas
    avoid_redundant_argument_values: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    no_logic_in_create_state: true
    sort_pub_dependencies: true
    use_rethrow_when_possible: true
    avoid_catches_without_on_clauses: true
    no_adjacent_strings_in_list: true
    public_member_api_docs: false  # Forzar la documentación de APIs públicas
    use_full_hex_values_for_flutter_colors: true  # Uso de valores hexadecimales completos para colores

    # Reglas de error
    cancel_subscriptions: true
    close_sinks: true
    hash_and_equals: true
    throw_in_finally: true
    unawaited_futures: true
    valid_regexps: true

    # Reglas adicionales
    avoid_null_checks_in_equality_operators: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_contains: true
    prefer_null_aware_operators: true
    prefer_spread_collections: true
    unnecessary_const: true
    unnecessary_new: true